Environment:
  executable: "executables/MADDPG_Windows"
  no_graphics: True
  n_rollout_threads: 8
  use_subprocess: True
  seed: 42
  time_scale: 20.0

ScaledProperties:
  ball_touch:
    init: 2.0
    final: 0.0
    n_episodes: 10000

Torch:
  rollout_dev: "cpu"
  train_dev: "cpu"
  n_training_threads: 8

Model:
  model_name: "Run-FINAL"
  load_from: null
  n_episodes: 30000
  max_steps: 1000
  steps_per_update: 512
  save_interval: 1000
  discrete_action: False
  Buffer:
    buffer_length: 1000000
    batch_size: 1024
  Exploration:
    n_exploration_eps: 30000
    init_noise_scale: 10.0
    final_noise_scale: 0.0
  Hyperparameters:
    hidden_units: 128
    actor_lr: 0.0003
    critic_lr: 0.0008
    tau: 0.001
    gamma: 0.90
