Environment:
  executable: "../executables/MADDPG_Windows"
  no_graphics: False
  n_rollout_threads: 2
  use_subprocess: False
  seed: 1

Torch:
  rollout_dev: "gpu"
  train_dev: "cpu"
  n_training_threads: 8

Model:
  model_name: "Try Run"
  load_from: null
  n_episodes: 10000
  max_steps: 1000
  steps_per_update: 100
  save_interval: 50
  discrete_action: False
  Buffer:
    buffer_length: 1000000
    batch_size: 1024
  Exploration:
    n_exploration_eps: 10000
    init_noise_scale: 1.0
    final_noise_scale: 0.0
  Hyperparameters:
    hidden_units: 128
    actor_lr: 0.0005
    critic_lr: 0.001
    tau: 0.001
    gamma: 0.99
