Environment:
  executable: "..\\CustomSoccer"
  no_graphics: False
  n_rollout_threads: 2
  use_subprocess: True
  seed: 1

Torch:
  rollout_dev: "cpu"
  train_dev: "cpu" 
  n_training_threads: 6

Model:
  model_name: "MADDPG_Default"
  continue_training: False
  n_episodes: 25000
  steps_per_update: 15
  save_interval: 2
  discrete_action: False
  Buffer:
    buffer_length: 1000000
    batch_size: 1024
  Exploration:
    n_exploration_eps: 25000
    init_noise_scale: 1.0
    final_noise_scale: 0.0
  Hyperparameters:
    hidden_units: 128
    tau: 0.01
    actor_lr: 0.0005
    critic_lr: 0.001
    tau: 0.001
    gamma: 0.99
